name: visionaray CI

on:
  push:
    branches: [ master, ci ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04]
        config: [Release, Debug]
        cuda: [ON, OFF]

    name: config ${{ matrix.config }} - CUDA ${{ matrix.cuda }}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Add NVIDIA package repositories
      if: >-
        matrix.os == 'ubuntu-24.04' &&
        matrix.cuda == 'ON'
      run: |
        wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-ubuntu2204.pin
        sudo mv cuda-ubuntu2204.pin /etc/apt/preferences.d/cuda-repository-pin-600
        sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/3bf863cc.pub
        sudo add-apt-repository "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/ /"
        sudo apt update

    - name: Install CUDA
      if: >-
        matrix.os == 'ubuntu-24.04' &&
        matrix.cuda == 'ON'
      run: sudo apt-get install -y cuda-toolkit-12-6

    - name: Install other dependencies
      if: matrix.os == 'ubuntu-24.04'
      run: sudo apt install -y libboost-all-dev libglew-dev freeglut3-dev libxi-dev libxmu-dev

    - name: Setup CUDA
      if: >-
        matrix.os == 'ubuntu-24.04' &&
        matrix.cuda == 'ON'
      run: |
        echo "/usr/local/cuda-12.6/bin" >> $GITHUB_PATH
        echo "LD_LIBRARY_PATH=/usr/local/cuda-12.6/lib64:$LD_LIBRARY_PATH" >> $GITHUB_ENV

    - name: Configure CMake
      env:
        CMAKE_PREFIX_PATH: opt
      run: >
        cmake -LA -B ${{github.workspace}}/build
        -DCMAKE_BUILD_TYPE=${{ matrix.config }}
        -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/build/install
        -DVSNRAY_ENABLE_EXAMPLES:BOOL=ON
        -DVSNRAY_ENABLE_VIEWER:BOOL=ON
        -DVSNRAY_ENABLE_COMMON:BOOL=ON
        -DVSNRAY_ENABLE_CUDA:BOOL=${{ matrix.cuda }}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{ matrix.config }} --target install
